### ISSUE TITLE
Unable to install from the setup.py file

### ISSUE THREAD

**Issue by anbarasanv** [Snooz82/robotframework-datadriver#21]
Hi Team,

I was tried this to install from setup.py files like below 
python -m  setup.py install
'
But getting below error:
Traceback (most recent call last):
  File "C:\jython2.7.2\Lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\jython2.7.2\Lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\jython2.7.2\Lib\runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "C:\jython2.7.2\Lib\pkgutil.py", line 478, in get_loader
    return find_loader(fullname)
  File "C:\jython2.7.2\Lib\pkgutil.py", line 488, in find_loader
    for importer in iter_importers(fullname):
  File "C:\jython2.7.2\Lib\pkgutil.py", line 439, in iter_importers
    __import__(pkg)
  File "<string>", line None
SyntaxError: Non-ASCII character in file '__pyclasspath__/setup.py', but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
PS D:\Trash\Robot\robotframework-datadriver-master>
PS D:\Trash\Robot\robotframework-datadriver-master>
PS D:\Trash\Robot\robotframework-datadriver-master>
PS D:\Trash\Robot\robotframework-datadriver-master> jython -m  setup.py install
Traceback (most recent call last):
  File "C:\jython2.7.2\Lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\jython2.7.2\Lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\jython2.7.2\Lib\runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "C:\jython2.7.2\Lib\pkgutil.py", line 478, in get_loader
    return find_loader(fullname)
  File "C:\jython2.7.2\Lib\pkgutil.py", line 488, in find_loader
    for importer in iter_importers(fullname):
  File "C:\jython2.7.2\Lib\pkgutil.py", line 439, in iter_importers
    __import__(pkg)
  File "<string>", line None
SyntaxError: Non-ASCII character in file '__pyclasspath__/setup.py', but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
PS D:\Trash\Robot\robotframework-datadriver-master> python -m  setup.py install
running install
running bdist_egg
running egg_info
creating src\robotframework_datadriver.egg-info
writing src\robotframework_datadriver.egg-info\PKG-INFO
writing dependency_links to src\robotframework_datadriver.egg-info\dependency_links.txt
writing requirements to src\robotframework_datadriver.egg-info\requires.txt
writing top-level names to src\robotframework_datadriver.egg-info\top_level.txt
writing manifest file 'src\robotframework_datadriver.egg-info\SOURCES.txt'
reading manifest file 'src\robotframework_datadriver.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pictout' under directory 'example'
warning: no files found matching '*.pictout' under directory 'atest'
writing manifest file 'src\robotframework_datadriver.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\DataDriver
copying src\DataDriver\AbstractReaderClass.py -> build\lib\DataDriver
copying src\DataDriver\csv_reader.py -> build\lib\DataDriver
copying src\DataDriver\DataDriver.py -> build\lib\DataDriver
copying src\DataDriver\generic_csv_reader.py -> build\lib\DataDriver
copying src\DataDriver\json_reader.py -> build\lib\DataDriver
copying src\DataDriver\pict_reader.py -> build\lib\DataDriver
copying src\DataDriver\ReaderConfig.py -> build\lib\DataDriver
copying src\DataDriver\rerunfailed.py -> build\lib\DataDriver
copying src\DataDriver\search.py -> build\lib\DataDriver
copying src\DataDriver\xlsx_reader.py -> build\lib\DataDriver
copying src\DataDriver\xls_reader.py -> build\lib\DataDriver
copying src\DataDriver\__init__.py -> build\lib\DataDriver
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\AbstractReaderClass.py -> build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\csv_reader.py -> build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\DataDriver.py -> build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\generic_csv_reader.py -> build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\json_reader.py -> build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\pict_reader.py -> build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\ReaderConfig.py -> build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\rerunfailed.py -> build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\search.py -> build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\xlsx_reader.py -> build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\xls_reader.py -> build\bdist.win-amd64\egg\DataDriver
copying build\lib\DataDriver\__init__.py -> build\bdist.win-amd64\egg\DataDriver
byte-compiling build\bdist.win-amd64\egg\DataDriver\AbstractReaderClass.py to AbstractReaderClass.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\DataDriver\csv_reader.py to csv_reader.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\DataDriver\DataDriver.py to DataDriver.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\DataDriver\generic_csv_reader.py to generic_csv_reader.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\DataDriver\json_reader.py to json_reader.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\DataDriver\pict_reader.py to pict_reader.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\DataDriver\ReaderConfig.py to ReaderConfig.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\DataDriver\rerunfailed.py to rerunfailed.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\DataDriver\search.py to search.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\DataDriver\xlsx_reader.py to xlsx_reader.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\DataDriver\xls_reader.py to xls_reader.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\DataDriver\__init__.py to __init__.cpython-38.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying src\robotframework_datadriver.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying src\robotframework_datadriver.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying src\robotframework_datadriver.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying src\robotframework_datadriver.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying src\robotframework_datadriver.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
DataDriver.__pycache__.DataDriver.cpython-38: module references __file__
creating dist
creating 'dist\robotframework_datadriver-0.4.0b1-py3.8.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing robotframework_datadriver-0.4.0b1-py3.8.egg
removing 'c:\python\lib\site-packages\robotframework_datadriver-0.4.0b1-py3.8.egg' (and everything under it)
creating c:\python\lib\site-packages\robotframework_datadriver-0.4.0b1-py3.8.egg
Extracting robotframework_datadriver-0.4.0b1-py3.8.egg to c:\python\lib\site-packages
robotframework-datadriver 0.4.0b1 is already the active version in easy-install.pth

Installed c:\python\lib\site-packages\robotframework_datadriver-0.4.0b1-py3.8.egg
Processing dependencies for robotframework-datadriver==0.4.0b1
Searching for Pygments==2.6.1
Best match: Pygments 2.6.1
Adding Pygments 2.6.1 to easy-install.pth file
Installing pygmentize-script.py script to C:\Python\Scripts
Installing pygmentize.exe script to C:\Python\Scripts

Using c:\python\lib\site-packages
Searching for docutils==0.16
Best match: docutils 0.16
Adding docutils 0.16 to easy-install.pth file

Using c:\python\lib\site-packages
Searching for robotframework==3.2.1
Best match: robotframework 3.2.1
Processing robotframework-3.2.1-py3.8.egg
robotframework 3.2.1 is already the active version in easy-install.pth
Installing rebot-script.py script to C:\Python\Scripts
Installing rebot.exe script to C:\Python\Scripts
Installing robot-script.py script to C:\Python\Scripts
Installing robot.exe script to C:\Python\Scripts

Using c:\python\lib\site-packages\robotframework-3.2.1-py3.8.egg
Finished processing dependencies for robotframework-datadriver==0.4.0b1
C:\Python\python.exe: Error while finding module specification for 'setup.py' (ModuleNotFoundError: __path__ attribute not found on 'setup' while trying to find 'setup.py')

jython -m  setup.py install

Error:
Traceback (most recent call last):
  File "C:\jython2.7.2\Lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\jython2.7.2\Lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\jython2.7.2\Lib\runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "C:\jython2.7.2\Lib\pkgutil.py", line 478, in get_loader
    return find_loader(fullname)
  File "C:\jython2.7.2\Lib\pkgutil.py", line 488, in find_loader
    for importer in iter_importers(fullname):
  File "C:\jython2.7.2\Lib\pkgutil.py", line 439, in iter_importers
    __import__(pkg)
  File "<string>", line None
SyntaxError: Non-ASCII character in file '__pyclasspath__/setup.py', but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
PS D:\Trash\Robot\robotframework-datadriver-master>
PS D:\Trash\Robot\robotframework-datadriver-master>
PS D:\Trash\Robot\robotframework-datadriver-master>
PS D:\Trash\Robot\robotframework-datadriver-master> jython -m  setup.py install
Traceback (most recent call last):
  File "C:\jython2.7.2\Lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\jython2.7.2\Lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\jython2.7.2\Lib\runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "C:\jython2.7.2\Lib\pkgutil.py", line 478, in get_loader
    return find_loader(fullname)
  File "C:\jython2.7.2\Lib\pkgutil.py", line 488, in find_loader
    for importer in iter_importers(fullname):
  File "C:\jython2.7.2\Lib\pkgutil.py", line 439, in iter_importers
    __import__(pkg)
  File "<string>", line None
SyntaxError: Non-ASCII character in file '__pyclasspath__/setup.py', but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by Snooz82** [comment]
Hi,

i never worked with Jython, but i think it is based on Python 2.7, right?
DataDriver uses some Python >= 3.6 stuff. A lot of f-strings and so on.

I think one issue is my name with a non ASCII Character... `René Rohner`

But i have a strong opinion against any Python 2.7 compatibility!!!
Python 2.7 MUST rest in peace! ;-)
