### ISSUE TITLE
Added Support for Pabot 1.3

### ISSUE THREAD

**Issue by Snooz82** [Snooz82/robotframework-datadriver#25]
Since v1.3 Pabot uses new parsing API and does not do DryRuns anymore.
Due to this interaction between Pabot and DataDriver needs to be updated.

Related to https://forum.robotframework.org/t/compatibility-of-pabot-1-3-with-datadriver-0-4-0/102

**Comment by davesliu** [comment]
@Snooz82 
Is current version of robotframework-datadriver  compatible with pabot 1.9.1?

**Comment by abomadev** [comment]
Hi @Snooz82 can you please give an estimate of when we can expect this update? 
The company I work for has datadriven tests which take 30hrs+ and we really need to parallelize the execution so speed things up.

**Comment by Snooz82** [comment]
It is. But `--testlevelsplit` does not work.

I am working on that issue.

**Comment by abomadev** [comment]
@Snooz82 That's great. Thank you.

Are you able to give a rough estimate when you think the `--testlevelsplit` feature would be ready? A few weeks, months? etc

**Comment by Snooz82** [comment]
Will be fixed with 1.0 Release
