### ISSUE TITLE
How to retest the failed test case when using the robotframwork-datadriver

### ISSUE THREAD

**Issue by davesliu** [Snooz82/robotframework-datadriver#26]
Hello,

The robotframework-datadriver is very helpful to generate test cases when reading different configuration params from .xlsx file.

With using the robotframework-datadriver and when some test cases failed. I want to retest the failed test cases.
The command: robot -R output.xml  Test.robot will fail as it can't parse the failed test cases due to the test case is newly generated by robotframework datadriver.

So How can we retest the failed test cases when using the robotframework datadriver?

**Comment by Snooz82** [comment]
Hi, 

There is a specific prerunmodifier for this case.

https://github.com/Snooz82/robotframework-datadriver#re-run-failed-test-cases

Cheers

**Comment by davesliu** [comment]
@Snooz82  
Thanks for your help. It solve my issues.
