### ISSUE TITLE
--prerunmodifier DataDriver.rerunfailed

### ISSUE THREAD

**Issue by bkarthickbtech** [Snooz82/robotframework-datadriver#27]
I have installed Robotframework, using Python2.7 on a linux machine. I have try to re-execute the failed test cases using this command   'robot --prerunmodifier   DataDriver.rerunfailed:output.xml   --output rerun.xml'. I am getting the following error,

Importing model modifier 'DataDriver.rerunfailed' failed: Module 'DataDriver' does not contain 'rerunfailed'.

**Comment by Snooz82** [comment]
@bkarthickbtech 

DataDriver is python 3 only!
there is just one "old" version 0.2.7 that is compatible to Python 2.7.
You must update your Python!

regards

**Comment by Snooz82** [comment]
This is the docs for DataDriver 0.2.7

https://pypi.org/project/robotframework-datadriver/0.2.7/
