### ISSUE TITLE
How can we read data from multiple sheets in a single test suite file?

### ISSUE THREAD

**Issue by sashan4u007** [Snooz82/robotframework-datadriver#28]
Scenario : In a single test case file, If we have two test cases and we have maintained test data for these two test cases in two separate sheets of same .xlsx file and we want to use sheet-1 in test-case-1 and sheet-2 in test-case2. 

Question : Is it possible using data-driver?

**Comment by Snooz82** [comment]
No that is not possible.

DataDriver requires only one TestTemplate and only one DataSource per Test Suite.
You can use the same file in multiple *.robot files for different test, but not in one file.

Cheers
