### ISSUE TITLE
how to implement the data driver with different configuration

### ISSUE THREAD

**Issue by davesliu** [Snooz82/robotframework-datadriver#32]
Hello.

I have a testObjectA.robot file with reading 1000 different parameters in a excel file, and it works very well with the robotframework-datadriver module by generate 1000 test cases.
Currently, we have to test the testObjectA.robot with 10 different pre-configuration. The way that we can do is add one column in the excel file for the 10 different configuration and copy & paste the 1000 parameters 10 times in excel file to generate 1000*10 test cases.

This way seems very low efficient and not easy to maintenance. Is any any better way than copy&past test parameters for the 10 different pre-configuration?

Thanks

**Comment by Snooz82** [comment]
Hi, you could use pabot to execute the same test suite 10 times and define that variable with argument files. But i am not that pro with pabot.

You could also write a custom DataReader that fetches that data from different table sheets/files. like multiplying each line with these 10 variants.

**Comment by davesliu** [comment]
@Snooz82 
Thanks for your comment. I use the first way as you suggested and it works.
