### ISSUE TITLE
Connection error in log file when using DataDriver with Browser library

### ISSUE THREAD

**Issue by frankyqa** [Snooz82/robotframework-datadriver#33]
I get this error message in the log file when I use DataDriver along with Browser library:

`Error in library 'Browser': Calling method '_close' of listener 'Browser' failed: failed to connect to all addresses`

I did not get a stack trace because the error does not interfere with test execution (yet). It is just displayed in the log file. My browser lib version is 1.3.0 and my DataDriver version is 0.3.3.
![image](https://user-images.githubusercontent.com/71194310/95753612-292d4500-0ca2-11eb-9537-4a36235835d9.png)

**Comment by Snooz82** [comment]
That should be a minor issue with Browser lib.
imho nothing on DataDriver side.

Can you please open an issue on Browser?
