### ISSUE TITLE
Pipeline Azure, file is not found

### ISSUE THREAD

**Issue by imdedios** [Snooz82/robotframework-datadriver#36]
How can I correct this error, I am having problems to run a robot file using DataDriver 

[ ERROR ] Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find D:\a\1\s\./private.csv but file does not exist.

********
```robotframework
*** Setting ***
Library          SeleniumLibrary
Library          DataDriver            file=private.csv    dialect=unix
```

**Comment by Snooz82** [comment]
@imdedios 

i would say, that there is no private.csv file in the same folder as this robot file?

Cheers

**Comment by Snooz82** [comment]
No response. I close it. Can be opened if necessary.
