### ISSUE TITLE
'keywords' attribute is read-only and deprecated since RF 4.0. Use 'body', 'setup', or 'teardown' instead

### ISSUE THREAD

**Issue by abhishek12sarkar** [Snooz82/robotframework-datadriver#37]
When upgraded to RF 4.0, getting this error ``'keywords' attribute is read-only and deprecated since RF 4.0. Use 'body', 'setup', or 'teardown' instead``.
The issue might be raised from _start_suite() method from DataDriver class.

Can this be fixed?
The changes required might be mentioned over here [#3749](https://github.com/robotframework/robotframework/issues/3749)

**Comment by rkefi84** [comment]
Facing same issue

**Comment by kumarkrish85** [comment]
Facing same issue from RF 4.0 , please advice how to resolve

**Comment by lucagiove** [comment]
`pip install --pre robotframework-datadriver`

fixes it

**Comment by Snooz82** [comment]
Yes i am working on that and i will release tomorrow.

**Comment by kumarkrish85** [comment]
Please share the updated example code

**Comment by lucagiove** [comment]
@kumarkrish85 You just have to install the newer version with the command I pasted above since it's a pre-release version

**Comment by kumarkrish85** [comment]
> @kumarkrish85 You just have to install the newer version with the command I pasted above since it's a pre-release version

Thanks ., I mean is there any change in earlier way of using the Data driver? If yes, please add an example

**Comment by lucagiove** [comment]
It shouldn't, the deprecation is inside the library itself how it calls RF api

**Comment by kumarkrish85** [comment]
> It shouldn't, the deprecation is inside the library itself how it calls RF api

Thanks for the confirmation

**Comment by Snooz82** [comment]
Fixed in Version 1.1.0 of DataDriver.
