### ISSUE TITLE
Test Teardown in DataDriver

### ISSUE THREAD

**Issue by m18v** [Snooz82/robotframework-datadriver#41]
Hello, 

I have realised that in current version Test Teardown using Data driver Library is not working. Can you please take a look if it is an issue ?

Regards,

**Comment by Snooz82** [comment]
Can you give me more context please?
Which version of DataDriver are you using and which robot version?

can you add an example test that reproduces that issue?

**Comment by Snooz82** [comment]
It can be opened again, if there is a reproduction possibility.
I close it due to no further information.

**Comment by Veronit** [comment]
Stumbled on this same error. Task/Test Teardown works on DataDriver version 1.0.0 but on the newer ones. Using RF version 3.2.2.
Attached is a sample test and log.html's for 
[datadriver.zip](https://github.com/Snooz82/robotframework-datadriver/files/6439791/datadriver.zip)
executions.
