### ISSUE TITLE
datadriver support for dictionary

### ISSUE THREAD

**Issue by Cerosh** [Snooz82/robotframework-datadriver#5]
I have recently tried out your Data driver library with excel and its working like charm and it’s really a great solution for many people including me who relays on data driven testing a lot.
The Data source that I use is dictionaries and not excel. I was wondering Data driven Library can help me to sort this problem. I am reaching out to you since I couldn’t find any documentation of data driver with dictionary.
Given below is a sample program format that we are using internally if you can share some insight it would be a great help.
 
*** Settings ***
Test Template    Example keyword
 
 
***Variables***
&{dictionary1}    argument=first     tag=first tag    
&{dictionary2}    argument=second     tag=second tag 
&{dictionary3}    argument=third    tag=third tag 
&{dictionary4}    argument=fourth     tag=fourth tag 
 
****Keywords***
Example keyword
    [Arguments]    ${dictionary}
   log    ${dictionary.argument}
   Set tags    ${dictionary.tag}
    
*** Test Cases **
Templated test case
    [Template]    Example keyword
    ${dictionary1}
    ${dictionary2}
    ${dictionary3}
    ${dictionary4}

**Comment by Snooz82** [comment]
I will have a look to this.
first i want to refactor the DataModell

Thanks for this input!

**Comment by Cerosh** [comment]
Thanks a lot, friend for your response. since I can convert from JSON to dictionary and back supporting Json would also solve the problem. Just wanted to share a thought if it helps you in any way.

**Comment by lucagiove** [comment]
I like this, I was thinking about the same, maybe whenever I need it I'll implement and submit a PR.
Basically will add test generator feature to RobotFramework.

**Comment by Snooz82** [comment]
Will be fixed in 4.0.0

**Comment by Snooz82** [comment]
Will be fixed with 1.0 Release
