### ISSUE TITLE
I can't setup data driver

### ISSUE THREAD

**Issue by ProfMostafa** [Snooz82/robotframework-datadriver#55]
I am trying to setup data driver and am getting the below error
ERROR: Could not find a version that satisfies the requirement robotframework-datadriver (from versions: none)

And I tried to search for this problem a lot and I couldn't resolve it, the below are the packages and python version what I have
Python                      3.9.6
pip                             21.1.3
robotframework                  3.2.2
robotframework-databaselibrary  1.2.4
robotframework-pabot            1.10.1
robotframework-pythonlibcore    2.2.1
robotframework-selenium2library 3.0.0
robotframework-seleniumlibrary  5.0.0
selenium                        3.141.0
setuptools                      56.0.0
urllib3                         1.26.3

**Comment by Snooz82** [comment]
Can you please post the full command line?
How did you try to install it?

**Comment by ProfMostafa** [comment]
Thanks a lot for your reply, I have resolved it, the problem was because SSL certificate
