### ISSUE TITLE
Enhancement: support AbstractReaderClass subclasses as reader_class argument value

### ISSUE THREAD

**Issue by robinmackaij** [Snooz82/robotframework-datadriver#58]
Subclassing DataDriver when there is a need to use a custom reader_class is somewhat cumbersome at the moment since the __init__ of DataDriver will try to resolve the reader_class based on filename. This can be improved by allowing AbstractReaderClass subclasses to be passed as the reader_class argument and having DataDriver check for subclass before trying to import the module from file path.

**Comment by Snooz82** [comment]
@robinmackaij That is fixed, right?!
