### ISSUE TITLE
Datadriver support for python 2.7

### ISSUE THREAD

**Issue by cfvergarac** [Snooz82/robotframework-datadriver#6]
I've been a long time using python 2.7 with robot framework, now I have to make an DDT automation, so  I want to use this library, but its incompatible with my python version. Could you make a compatible version?

**Comment by Snooz82** [comment]
Just as question:
Dint you get a warning from PIP that this version is not supported?

**Comment by cfvergarac** [comment]
NO, I didn't

**Comment by Snooz82** [comment]
I will see what i can do.
If the effort is not too big, i will release a single version for python 2.7.


Something like a warning in PIP.
„Actual Version of DataDriver is incompatible with your Python version.
Use 'pip install -U robotframework-datadriver==0.2.27'

Would this work for you?
I don't want to develop on a deprecated programming language new features.

**Comment by cfvergarac** [comment]
Sure René, that will be util. Im going to change to python 3 as my project
interpreter.

Thanks a lot for your help.

**Comment by Snooz82** [comment]
there is now a python27 compatible Version available over Pip.
0.2.7
