### ISSUE TITLE
Datadriver not picking up test case name from CSV

### ISSUE THREAD

**Issue by hbirkdale** [Snooz82/robotframework-datadriver#62]
I thought I saw in tutorials that DataDriver would pick up test case names from the CSV file, but that doesn't seem to be happening for me. The tests are definitely running, and the [Documentation] data is being picked up. Here is my setup:
**DATA**
```csv
*** Test Cases ***,${username},${password},${email},${url_complete},[Tags],[Documentation]
Register New User,hgb55,xxxyyy,hb+tester@somecompany.com,${success_url},,Manually confirm this user does not exist already
Try and register existing user,hgb55,xxxzzz,hb+tester@somecompany.com,${registration_url},,
Try a password that is too simple,hb999,what,hb+tester@somecompany.com,${registration_url},,
Try another password that is too simple,hb999,whatever,hb+tester@somecompany.com,${registration_url},,
```

**TASKS.ROBOT**
```robotframework
*** Settings ***
Documentation     Main test suite for registering deals users.
Library           RPA.Browser.Selenium
Library           OperatingSystem
Library           DataDriver    Deals.csv    dialect=userdefined    delimiter=,    encoding='utf-8'
Resource          ../.env.robot
Test Template     Register as a deals user
Suite Teardown    Close all browsers

*** Variables ***
${registration_url}    ${HOST}/deals/registerusers/    # Don't change variable name - in CSV file too.
${success_url}    ${HOST}/accounts/register/complete/    # Don't change variable name - in CSV file too.

*** Test Cases ***
Register with user '${username}' and password '${password}'
    Default    UserData
```
followed by the "Register as a deals user" keyword - which does execute.

Am I missing something?

**Comment by Snooz82** [comment]
Hi @hbirkdale,

can you put you console output here?
What are the names you get?

**Comment by hbirkdale** [comment]
Hi @Snooz82 
Here's a screen shot - its basically taking the single *** Test Case *** from task.robot and creating the test cases from it.
![image](https://user-images.githubusercontent.com/5109603/137546258-3eec71d8-79bf-40b7-8082-d7e1237e3cd8.png)

**Comment by hbirkdale** [comment]
Sorry @Snooz82 - just realized i had posted some pws....here is the update

![image](https://user-images.githubusercontent.com/5109603/137547984-49a88595-d322-4285-8b0b-dffccf30ae0a.png)

**Comment by Snooz82** [comment]
That is interesting and not as designed/intended.

i will check that

**Comment by hbirkdale** [comment]
@Snooz82 You were right - that was it. As soon as I changed the encoding it the test case names came from the CSV. Thanks!
