### ISSUE TITLE
Escaping commas in dictionary variables

### ISSUE THREAD

**Issue by chaosseed** [Snooz82/robotframework-datadriver#69]
Hello. Could someone please tell me how to escape commas in dict variables?

I have dict varibale in xlsx file like below:

&{expected_message}
code=1,message=Date is a required field, but was not found...

Already tried adding \,\\ or \\\\ before comma yet still getting error like 

_Invalid dictionary variable item "but was not found..."_

Thank you

**Comment by Snooz82** [comment]
It is not designed to escape comma.
I think you have to work with two columns.

```
&{expected_message.code};&{expected_message.message}
1;Date is a required field, but was not found...
```

**Comment by chaosseed** [comment]
> It is not designed to escape comma. I think you have to work with two columns.
> 
> ```
> ${expected_message.code};${expected_message.message}
> 1;Date is a required field, but was not found...
> ```

Thank you for the clarification. I will update my sheet then.
