### ISSUE TITLE
Data Driver is not picking the file created in suite setup

### ISSUE THREAD

**Issue by RohKumarT** [Snooz82/robotframework-datadriver#71]
Hello, Thank you for the great work!
I am facing the below issue , would you be able to help.?

Issue:
I am downloading a csv file in suite setup, and using the same file in DataDriver library. Is it possible.?
Because as i got to know from video that DataDriver loads the file before the suite setup, is it correct.?
Is there any work around.?Or can it be enhanced to take the file created during suite setup.?
Thank you

**Comment by Snooz82** [comment]
Sure that is possible.
But not with suite setup.

https://github.com/Snooz82/robotframework-datadriver#configure-datadriver-by-pre-run-keyword

you implement a config keyword.
