### ISSUE TITLE
[feature request] Add ability to provide extra arguments to 'pict'

### ISSUE THREAD

**Issue by Apteryks** [Snooz82/robotframework-datadriver#72]
Hello,

While using DataDriver with pict (really cool!), I found myself wanting to provide an extra option to the underlying `pict` command invocation (`/o:5` for example).  

So this ticket is a feature request to be able to do so like, for example:

```
Library    DataDriver    model.pict    extra_args=['/o:5', ... ]
```
I'm not sure what the usual format to provide a list of arguments in RobotFramework; if only a string is accepted (and need to be parsed), it could be a comma-separated value instead of the above.

Thank you!

**Comment by Snooz82** [comment]
@Apteryks 

This is now possible
Argument is called `pict_options=` you do not need an array.
just write the arguments.
like: `pict_options=/o:5 /r`

Fixed with 1.6.0

**Comment by Apteryks** [comment]
Thank you!

**Comment by Apteryks** [comment]
For the record, I wanted this to combine it with this change: https://github.com/Apteryks/pict/commit/cd5422202b25d0f3f3896c7fe314a9a76761f1d1; then it becomes trivial to use a .pict file and test *all* combinations.

**Comment by Snooz82** [comment]
Cool that this is now in as well!

you are by the way the first i know, who is really using DataDriver with PICT.

i always thought this is a cool combination but until now, no one that i know used it.

**Comment by Apteryks** [comment]
I decided trying it after stumbling on a 256 combinations test and reading about it in the README.  I'm using GNU Guix to manage my development environment and all the bits are readily packaged:
`guix shell python python-robotframework python-robotframework-datadriver pict` :-).
