### ISSUE TITLE
[Documentation] field on Test Case template not honored

### ISSUE THREAD

**Issue by Apteryks** [Snooz82/robotframework-datadriver#74]
Hello,

When using a test template such as:

```
*** Test Cases ***
 Some Test ${param1} ${param2} ...
    [Documentation]    Some documentation for the test.
```

The documentation is not shown next to each test in the test report.

**Comment by Snooz82** [comment]
in 1.7.0 if no `[Documentation]` is defined in the source, so if the TestCaseData.documentation is `None` and not "" the template doc is used.
