### ISSUE TITLE
Pabot Data Driver optimization

### ISSUE THREAD

**Issue by appusri9** [Snooz82/robotframework-datadriver#77]
I have 10k test cases in excel and used Data driver test template with optimize_pabot=Binary. Am using pabot  for parallel execution with 10 processes but in the result I see pabot form 59 executions. Could u pls help me understand how the optimize_pabot options are working?? Though I initiated 10 processes i see 59 executions and how is that possible?? Also  in a machine with 4vCPU and 16GB memory how many processes can be launched to run in parallel?? If the number of processes are more i see it is taking more time for execution what could be the reason behind it. Thank in Advance

**Comment by Snooz82** [comment]
if you only want 10 pabot runs with 1000 test cases each, that you should select `equal` and not `binary` .

I think it is explained here?
https://github.com/Snooz82/robotframework-datadriver#pabot-and-datadriver

Would be best to ask questions in Slack (robotframework.slack.com) or forum.robotframework.org
