### ISSUE TITLE
Unable to import robotframework-datadriver

### ISSUE THREAD

**Issue by RushikSantoki** [Snooz82/robotframework-datadriver#80]
**robotframework==4.1.3
ride==0.7.2
robotframework-datadriver==1.6.1**

I am unable to import datadriver. (It is shown in red, implying failure in importing).
The driver is installed properly and I verified it using pip freeze.

I have mentioned the robotframework, ride and datadriver versions above.

**Comment by Snooz82** [comment]
I am pretty sure that this is an issue for RIDE.

by the way: i know that ride has not release new versions on PyPi, but you can install current ride versions directly from Github.

`pip install -U https://github.com/robotframework/RIDE/archive/master.zip`
