### ISSUE TITLE
DataDriver Run in Python with tags (include)

### ISSUE THREAD

**Issue by Krata4** [Snooz82/robotframework-datadriver#86]
Hello, I would like ask you regarding run tests with datadriver via Python run. Tags are not accepted and all test run. 
Example:
1) Command line robot --outputdir Results -i test Tests/Webchat.robot = WORKING
2) Python - option_dic = { "outputdir": f'Results', "include":"test"} **run(f'Tests/Webchat.robot', **option_dic)** = NOT WORKING
3) Python - run(f'Tests/', **option_dic, variable=variables, suite=suite,include=["test"]) - NOT WOKRING

NOT WORKING mens:
In Python file I am not able to run tests with tags. Still all tests are triggered.

**Comment by Krata4** [comment]
Hello,

any progress in this issue please?

Thanks
Jirka

**Comment by Krata4** [comment]
Hello, 

please, any progress?

Thanks

**Comment by Snooz82** [comment]
Proposal is to additionally read the OPTIONS robot variables.
At the moment DataDriver does use the sys.argv and let it analyse by robots argument parser.
Therefore it is not possible for DataDriver to get includes that are not part of the sys.argv.

`&{OPTIONS}': {'include': [], 'exclude': ['EXCL'], 'skip': ['SKIP'], 'skip_on_failure': []}`

**Comment by Snooz82** [comment]
that OPTIONS variable would require RF 5.0

**Comment by Krata4** [comment]
Hello,

but your proposal is my option 2:

option_dic = { "outputdir": f'Results', "include":"test"} 
run(f'Tests/Webchat.robot', option_dic) = NOT WORKING

am I right? This is not working

**Comment by Snooz82** [comment]
I think that option should not work in general.
Afaik you have to unpack the option_dict with **option_dict or as single named args.

but anyway. If version 2 works, then 1, 2 and 3 would work with my proposal.
