### ISSUE TITLE
Testcases do not get executed

### ISSUE THREAD

**Issue by QCube** [Snooz82/robotframework-datadriver#9]
Since version 0.3.1 my datadriver testcases are not being executed properly. The tests do not fail, they pass whilst simply not being executed. The strange thing is, DataDriver seems to run properly and even sees the testcases but is just skipping them.

Console Output (DEBUG):
...
[ DataDriver ] Initialized in xlsx-mode.
[ DataDriver ] Reader Module: <module 'DataDriver.xlsx_reader' from 'c:\\program files (x86)\\python36-32\\lib\\site-packages\\DataDriver\\xlsx_reader.py'>
[ DataDriver ] Opening file 'C:\...\ ../nameChanged.xlsx'
[ DataDriver ] 11 Test Cases loaded...
Web App.Someapp.Load Something.Load Something :: Documentationstring, ... | PASS |
0 critical tests, 0 passed, 0 failed
0 tests total, 0 passed, 0 failed
...

Versions:
python                                                 3.6.8 (32 bit)
robotframework                                   3.1.2
robotframework-datadriver                  0.3.1

**Comment by Snooz82** [comment]
Hi,

Do you use --include or --exclude to filter for TestCases?

in 3.1 filter by tags has been added...

**Comment by QCube** [comment]
Hi,
I've read that but now I see where the problem lies:
We use argument files to filter with --include (-i). But we don't use the "[Tags]" collumn statet as being optional in the documentation. Still the Datadriver excludes the testcases. (if I include the collumn and the tags it works, but for my specific case I don't want to add tags in the excel sheet)

I would suggest either adding an explicit flag to deactivate or activate filtering by tags or, probably even better, not to filter for tags if there is no "[Tags]" collumn (as it is explained being optional anyway).

**Comment by Snooz82** [comment]
Ok.
I will think about this situation.
How urgent is it?

**Comment by Snooz82** [comment]
Can you workaround with v3.0?

**Comment by QCube** [comment]
It's not very urgent, v3.0 is sufficient for us right now.

**Comment by Snooz82** [comment]
Hi,

This issue should be solved.
When no Tags column is set, all testcases will be included if suite is included.

Could you please check with DataDriver v 0.3.2?
And give feedback?

**Comment by QCube** [comment]
Hi,

It seems like it's resolved now.
My testcases get executed without a tag column, don't get executed if a tag column is available and no matching tags are given and the tests specified by a matching tag get executed properly as well.

Thank you a lot!
