### ISSUE TITLE
Rerun failed tests raise an error in the latest 1.11.0 version

### ISSUE THREAD

**Issue by wanghui-00** [Snooz82/robotframework-datadriver#96]
Rerun failed cases with example command `robot --prerunmodifier DataDriver.rerunfailed:output.xml --output rerun.xml test.robot` 
are failed in the latest 1.11.0 version

```
Importing model modifier 'DataDriver.rerunfailed' failed: ImportError: cannot import name 'Variable' from 'robot.running.model' (C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\robot\running\model.py)
Traceback (most recent call last):
  File "C:\Users\***1\AppData\Local\Programs\Python\Python39\lib\site-packages\DataDriver\rerunfailed.py", line 8, in <module>
    from robot.running.model import Variable  # type: ignore
```

This action is success in old version 1.9.0, but it didn't support latest robotframework 7.0

**Comment by tomasnemecek1** [comment]
I'm facing the same issue - running Robot Framework 7.0 and DataDriver library 1.11.0.  As a result all the tests and run again, not only those failed ones.

**Comment by Snooz82** [comment]
fixed.

https://pypi.org/project/robotframework-datadriver/1.11.1/
